name: Dart CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.8.1"
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "2.15.1"

      - name: Set environment
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Get dependencies
        run: |
          dart pub global activate melos
          melos run pub:get
      - name: Release
        uses: softprops/action-gh-release@v1
